# Configuration pour le profil 'local' : identique à application.yml
# sauf les propriétés de datasource qui pointent vers un Postgres local (Docker)
spring:
  application:
    name: iot-playground
  datasource:
    url: jdbc:postgresql://localhost:5432/iot_playground_local
    username: iot_user
    password: iot_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  thymeleaf:
    cache: false
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.sentori.iot: DEBUG
  file:
    path: ./logs

app:
  base-url: http://localhost:8080
  sensor:
    ingest-path: /sensors/data
  grafana:
    base-url: http://localhost:3000
    # UID + slug du dashboard
    dashboard-path: /d/sensors-temp-v2/sensors-temperature-par-capteur-user-run-v2

    org-id: 1
    ds-prom-uid: dew0ddwep0p34d
    timezone: browser
    default-from: now-15m
    default-to: now
    default-refresh: 5s
  reports:
    api-gateway-url: ${REPORTS_API_GATEWAY_URL}
    api-key: ${REPORTS_API_KEY}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Configuration AWS X-Ray
com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:127.0.0.1:2000}
      context-missing: LOG_ERROR